### ISSUE TITLE
Layer comps selection as (radio) buttons

### ISSUE THREAD

**Issue by dinko** [ozgurgunes/Sketch-Layer-Comps#2]
A UX suggestion: to save a click and pointing effort, it would be nice to show selectable comps as radio buttons or, even better, just buttons to save another click on the "Apply" button. The dropdown is a bit cumbersome.

**Comment by ozgurgunes** [comment]
Thank you for suggestion. I completely rewritten the plugin with same old interface. While I working I occasionally prefer to run plugin with keyboard shortcut, hit down arrow to open dropdown list, down arrows to select, then enter 2 times to apply. This is really fast way to use the plugin. I'll try your suggestion, be sure it will be updated as your suggestion If I manage to use with keyboard in that way.

**Comment by ozgurgunes** [comment]
Sorry. I could not manage that work.
