### ISSUE TITLE
Feature request: Artboard/Symbol support

### ISSUE THREAD

**Issue by lfs-designsystem** [ozgurgunes/Sketch-Layer-Comps#6]
I'd love to be able to use this kind of override in symbols to turn layers on/off at will. Would be really useful for switching states for more complex patterns in our design system. Happy to show examples and or test out if I can help in any way.

**Comment by ozgurgunes** [comment]
Try this for symbols please:
https://github.com/ozgurgunes/Sketch-Symbol-States
